config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
    resources :posts do
      collection do
      post :confirm
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }
  mount_uploader :picture, PictureUploader

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }

  validates :name, presence: true, length: {maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "つぶやきを投稿しました！"
      else
        render :new
      end
    end
  end

  def show
  end


  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "つぶやきを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "ブログを削除しました！"
  end


  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(:content, :picture, :picture_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>fb_App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
    <h2><%= @post.errors.count %>件のエラーがあります。</h2>
    <ul>

    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="post_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="image_field">
    <%= form.label :picture %>
    <%= image_tag(@post.picture.url, style:'width:200px;height:170px') if @post.picture && @post.picture.url %>
    <%= form.file_field :picture %>
  </div>

  <%= form.submit %>

<% end %>

<%= link_to "投稿一覧に戻る", posts_path, class: "btn btn-info" %>

app/views/posts/confirm.html.erb
<h3>以下の内容で、投稿する</h3>

<%= form_with(model: @post, url: posts_path,local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @post.content %></p>

  <%= image_tag(@post.picture.url,style:'width:400px;height:240px') if @post.picture && @post.picture.url %>
  <%= form.hidden_field :picture_cache %>

  <%= form.submit "登録する" %>

  <%= form.submit "戻る", name: 'back' %>

<% end %>

app/views/posts/edit.html.erb
<h2>Editing Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>つぶやき一覧</h1>

<table>
  <tr>
    <th>名前</th>
    <th>内容</th>
    <th>写真</th>
    </tr>


<% @posts.each do |post| %>
  <tr>
    <td><%= post.user.name %></td>
    <td><%= post.content %>
    <td><%= image_tag post.picture.url, style:'width:400px;height:240px' if post.picture_url %></td>
    <td><%= link_to '詳細を確認する', post_path(post.id), class: "btn btn-secondary" %></td>
    <td><%= link_to 'つぶやきを編集する', edit_post_path(post.id), data: { confirm: '本当に編集していいですか？' }, class: "btn btn-dark" %>
    </td>
    <td><%= link_to 'つぶやきを削除する', post_path(post.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<%= link_to '新しくブログを投稿する', new_post_path, class: "btn btn-warning" %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>ポスト詳細画面</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>写真: <%= image_tag @post.picture.url, style:'width:400px;height:240px' if @post.picture_url %></p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>prohibited this<%= @user.name %>from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model:@user, local:true ) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to 'ポスト投稿', new_post_path, class: "btn btn-info" %>